---
name: analysis
display-name: anaLYsis
short-description: Graphical highlighing for musical analysis with GNU LilyPond
description: >
  To be done.
modules:
dependencies:
maintainers:
- Klaus Blum 
    email: <TODO>
- Urs Liska
    email: ul@openlilylib.org
    website: https://openlilylib.org
version: 0.0.1
license: GPL3
repository: https://github.com/openlilylib/analysis/
website:
---
